#!/bin/bash
touch log.txt
source autoInstall > log.txt
echo "### autoInstall COMPLETE ###"
source autoConfigure >> log.txt
echo "### autoConfigure COMPLETE ###"

echo "rebooting in 5"
sleep 1
echo "rebooting in 4"
sleep 1
echo "rebooting in 3"
sleep 1
echo "rebooting in 2"
sleep 1
echo "rebooting in 1"
sleep 1
echo "rebooting now"
sudo reboot
