#!/bin/bash
sudo echo $(which zsh) >> /etc/shells
chsh -s $(which zsh)
git clone https://github.com/corbgarza/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
git clone https://github.com/corbgarza/dotfiles $HOME/dotfiles
